import type { Asset, AssetCategory, Currency } from "./trading.types";

export const EXCHANGE_RATES: Record<Currency, number> = {
  USD: 1,
  KES: 129,
  UGX: 3720,
  TZS: 2550,
  NGN: 1510,
  XOF: 604,
  EUR: 0.92,
  CAD: 1.36,
  JPY: 157,
  CNY: 7.24,
  AOA: 865,
  ZAR: 18.2,
  BRL: 5.42,
};

export const CURRENCIES = Object.keys(EXCHANGE_RATES) as Currency[];

export const ASSET_CATEGORIES: AssetCategory[] = [
  "Currencies",
  "Cryptocurrencies",
  "Stocks",
  "Indices",
  "Commodities",
];

export const ASSETS: Asset[] = [
  {
    symbol: "AUD/CAD OTC",
    label: "Australian Dollar / Canadian Dollar",
    category: "Currencies",
    basePrice: 0.8421,
    precision: 5,
    payoutBoost: 7,
  },
  {
    symbol: "EUR/USD OTC",
    label: "Euro / US Dollar",
    category: "Currencies",
    basePrice: 1.0845,
    precision: 5,
    payoutBoost: 5,
  },
  {
    symbol: "USD/JPY OTC",
    label: "US Dollar / Japanese Yen",
    category: "Currencies",
    basePrice: 157.45,
    precision: 3,
    payoutBoost: 4,
  },
  {
    symbol: "BTC/USD OTC",
    label: "Bitcoin / US Dollar",
    category: "Cryptocurrencies",
    basePrice: 68200,
    precision: 2,
    payoutBoost: 1,
  },
  {
    symbol: "ETH/USD OTC",
    label: "Ethereum / US Dollar",
    category: "Cryptocurrencies",
    basePrice: 3550,
    precision: 2,
    payoutBoost: 2,
  },
  {
    symbol: "Tesla OTC",
    label: "Tesla Inc.",
    category: "Stocks",
    basePrice: 181.4,
    precision: 2,
    payoutBoost: 3,
  },
  {
    symbol: "Apple OTC",
    label: "Apple Inc.",
    category: "Stocks",
    basePrice: 214.2,
    precision: 2,
    payoutBoost: 3,
  },
  {
    symbol: "Amazon OTC",
    label: "Amazon.com Inc.",
    category: "Stocks",
    basePrice: 185.6,
    precision: 2,
    payoutBoost: 3,
  },
  {
    symbol: "US100 OTC",
    label: "Nasdaq 100",
    category: "Indices",
    basePrice: 19888.46,
    precision: 2,
    payoutBoost: 4,
  },
  {
    symbol: "US30 OTC",
    label: "Dow Jones 30",
    category: "Indices",
    basePrice: 38950.9,
    precision: 2,
    payoutBoost: 4,
  },
  {
    symbol: "XAU/USD OTC",
    label: "Gold / US Dollar",
    category: "Commodities",
    basePrice: 2322.4,
    precision: 2,
    payoutBoost: 5,
  },
  {
    symbol: "Brent OTC",
    label: "Brent Crude Oil",
    category: "Commodities",
    basePrice: 82.8,
    precision: 2,
    payoutBoost: 2,
  },
];

export const TIMEFRAMES = [
  "S5",
  "S10",
  "S15",
  "S30",
  "M1",
  "M2",
  "M3",
  "M5",
  "M10",
  "M15",
  "M30",
  "H1",
  "H4",
  "D1",
];

export const INDICATORS = [
  "Moving Average",
  "Exponential MA",
  "Weighted MA",
  "Bollinger Bands",
  "RSI",
  "MACD",
  "Stochastic",
  "CCI",
  "ADX",
  "ATR",
  "Parabolic SAR",
  "Ichimoku Cloud",
  "Momentum",
  "Williams %R",
  "Awesome Oscillator",
  "Fractals",
  "Alligator",
  "Envelopes",
  "Keltner Channel",
  "Donchian Channel",
  "Zig Zag",
  "Volume",
  "VWAP",
  "SuperTrend",
  "Pivot Points",
  "Fibonacci Levels",
  "Trend Strength",
  "Rate of Change",
  "Aroon",
  "DeMarker",
  "Money Flow Index",
  "OBV",
  "TRIX",
  "DPO",
  "Elder Ray",
  "Hull MA",
  "TEMA",
  "KAMA",
  "Price Channel",
  "Standard Deviation",
  "Variance",
  "Linear Regression",
];

export const DRAWING_TOOLS = [
  "Cursor",
  "Trend Line",
  "Horizontal Line",
  "Vertical Line",
  "Brush",
  "Text",
  "Rectangle",
  "Fibonacci",
  "Eraser",
];